[package]
name = "streamson-bin"
version = "4.0.0"
authors = ["Stepan Henek <stepan@henek.name>"]
edition = "2018"
description = "A program which processess large JSON input and splits them into a small ones."
license = "MIT"
readme = "README.md"
keywords = ["json"]
repository = "https://github.com/shenek/streamson"
categories = ["parsing"]

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
clap = "2.33"
streamson-lib = { version = "4.0.0", path = "../streamson-lib/" }
